### ISSUE TITLE
git checkout

### ISSUE THREAD

**Issue by MelinaKlostermann** [YeoLab/Mudskipper#1]
Hi,

I am trying to download Mudskipper inside a docker container. But the git checkout step does not seem to work. I am sorry if it might be a naive question!

Here is what I am doing:

`
docker run -it snakemake/snakemake:latest
wget https://github.com/algaebrown/oligoCLIP.git
git checkout oligo-pe
`

And this is the error that I get: error: 
pathspec 'oligo-pe' did not match any file(s) known to git

Also, I was wondering if I should download wget https://github.com/algaebrown/oligoCLIP.git and not https://github.com/YeoLab/Mudskipper.git instead?

**Comment by MelinaKlostermann** [comment]
Ok I think I found the first mistake, which is to clone the repository :) But the check out still does not work


(base) mklostermann@koenighpc:~$ git clone https://github.com/algaebrown/oligoCLIP.git

Cloning into 'oligoCLIP'...
remote: Enumerating objects: 1547, done.
remote: Counting objects: 100% (1013/1013), done.
remote: Compressing objects: 100% (425/425), done.
remote: Total 1547 (delta 674), reused 855 (delta 546), pack-reused 534
Receiving objects: 100% (1547/1547), 27.64 MiB | 35.29 MiB/s, done.
Resolving deltas: 100% (815/815), done.

(base) mklostermann@koenighpc:~$ cd oligoCLIP

(base) mklostermann@koenighpc:~/oligoCLIP$ git checkout oligo-pe

error: pathspec 'oligo-pe' did not match any file(s) known to git

(base) mklostermann@koenighpc:~/oligoCLIP$ ls
all.svg                  README.md                snakeDros_config.py
anno.svg                 rules                    snakeDros.py
CC.svg                   scripts                  Snake_peakanno_chi.py
config                   snakeCLIP.py             Snake_PeakMain.py
External.svg             snakeCLIP.svg            snake_SMINPUT_peaks.py
InvRiL19_adapters.fasta  Snake_downbam.py         Snake_test_diff_bg.py
make_csv.py              Snake_downbam_UMI_PE.py  snake_uniqueDros.py
__pycache__              Snake_downbam_UMI.py     snake_variability.py

(base) mklostermann@koenighpc:~/oligoCLIP$ cd ..

(base) mklostermann@koenighpc:~$ git checkout oligo-pe

fatal: not a git repository (or any parent up to mount point /media)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by algaebrown** [comment]
Hi Melina, Thank for trying out mudskipper. This was a wrong command which was from the old repository.
To download, instead use `git clone https://github.com/YeoLab/Mudskipper.git`.  I have updated readme. And the main branch should be the main software. 

I do notice the dependencies (`JAVA_PATH` etc) might be hard to install so we are working on containerizing all of them.

**Comment by MelinaKlostermann** [comment]
Ok, thanks!

**Comment by algaebrown** [comment]
Hi Melina, I merged the containerized branch to main and lab member helped me test. It should be easier to use now. lmk if you still run into problems

**Comment by MelinaKlostermann** [comment]
Thanks a lot,

the installation worked now for me also in docker instead of singularity!

```
docker run -it continuumio/anaconda3
conda env create -f rules/envs/snakemake.yaml -n my_snakemake_env
conda activate my_snakemake_env
```
