### ISSUE TITLE
Is 10G enough memory for the alignment step?

### ISSUE THREAD

**Issue by byee4** [YeoLab/Mudskipper#2]
https://github.com/YeoLab/Mudskipper/blob/3ffec0f28d4507dacc900eb0a0b67e30b14e67ce/rules/map_r1.smk#L26

**Comment by algaebrown** [comment]
Hi Brian, this rule is only used during debug and will not be triggered during a normal run. I think 10 G is not enough though

**Comment by byee4** [comment]
Thanks for clarifying!
