### ISSUE TITLE
Needs scipy installed in main environment

### ISSUE THREAD

**Issue by byee4** [YeoLab/Mudskipper#3]
https://github.com/YeoLab/Mudskipper/blob/f168e1f1902b2c54a2d5c4b0a76c33ff3da5655a/rules/QC.smk#L144C1-L145C1

**Comment by algaebrown** [comment]
Hi Brian, it is fixed in commit. added dependency into .yaml and readme. 
https://github.com/YeoLab/Mudskipper/commit/8ca32189c21b86a7c355104564b29b78b5ced0e9

**Comment by byee4** [comment]
Got it, thanks!
